const companies={
  NVIDIA:{ticker:'NVDA',color:'#76b900'},
  Microsoft:{ticker:'MSFT',color:'#ffd84d'},
  Apple:{ticker:'AAPL',color:'#c9ced6'}
};

const reports=[
  {c:'NVIDIA',q:'Q4 FY24',d:'2024-02-21',r:22.1,mc:1.67,pe:57,rx:9.1,t:['ai','data center','growth','demand'],x:'Record quarterly revenue of $22.1 billion, up 22% from Q3 and up 265% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2024/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2024/'},
  {c:'NVIDIA',q:'Q1 FY25',d:'2024-05-22',r:26.0,mc:2.35,pe:60,rx:9.3,t:['ai','data center','demand','supply'],x:'Record quarterly revenue of $26.0 billion, up 18% from Q4 and up 262% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2024/NVIDIA-Announces-Financial-Results-for-First-Quarter-Fiscal-2025/'},
  {c:'NVIDIA',q:'Q2 FY25',d:'2024-08-28',r:30.0,mc:2.90,pe:55,rx:-6.4,t:['ai','data center','supply','margin'],x:'Record quarterly revenue of $30.0 billion, up 15% from Q1 and up 122% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2024/NVIDIA-Announces-Financial-Results-for-Second-Quarter-Fiscal-2025/'},
  {c:'NVIDIA',q:'Q3 FY25',d:'2024-11-20',r:35.1,mc:3.58,pe:54,rx:-3.2,t:['ai','data center','blackwell','supply'],x:'Record quarterly revenue of $35.1 billion, up 17% from Q2 and up 94% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2024/NVIDIA-Announces-Financial-Results-for-Third-Quarter-Fiscal-2025/'},
  {c:'NVIDIA',q:'Q4 FY25',d:'2025-02-26',r:39.3,mc:3.00,pe:43,rx:-8.5,t:['ai','data center','blackwell','margin'],x:'Record quarterly revenue of $39.3 billion, up 12% from Q3 and up 78% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2025/'},
  {c:'NVIDIA',q:'Q1 FY26',d:'2025-05-28',r:44.1,mc:3.39,pe:45,rx:3.2,t:['ai','china','risk','demand'],x:'Revenue for the first quarter was $44.1 billion, up 12% from the previous quarter and up 69% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Announces-Financial-Results-for-First-Quarter-Fiscal-2026/'},
  {c:'NVIDIA',q:'Q2 FY26',d:'2025-08-27',r:46.7,mc:4.28,pe:51,rx:-1.8,t:['ai','data center','china','risk'],x:'Revenue for the second quarter was $46.7 billion, up 6% from the previous quarter and up 56% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Announces-Financial-Results-for-Second-Quarter-Fiscal-2026/'},
  {c:'NVIDIA',q:'Q3 FY26',d:'2025-11-19',r:57.0,mc:4.47,pe:47,rx:5.0,t:['ai','data center','demand','growth'],x:'Record revenue for the third quarter was $57.0 billion, up 22% from the previous quarter and up 62% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2025/NVIDIA-Announces-Financial-Results-for-Third-Quarter-Fiscal-2026/'},
  {c:'NVIDIA',q:'Q4 FY26',d:'2026-02-25',r:68.1,mc:4.62,pe:42,rx:2.6,t:['ai','data center','rubin','investment'],x:'Record quarterly revenue of $68.1 billion, up 20% from Q3 and up 73% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2026/'},
  {c:'NVIDIA',q:'Q1 FY27',d:'2026-05-20',r:81.6,mc:5.05,pe:40,rx:4.7,t:['ai','data center','demand','investment'],x:'Record revenue for the first quarter was $81.6 billion, up 20% from the previous quarter and up 85% from a year ago.',u:'https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-First-Quarter-Fiscal-2027/default.aspx'},

  {c:'Microsoft',q:'Q2 FY24',d:'2024-01-30',r:62.0,mc:3.02,pe:37,rx:-2.7,t:['ai','cloud','growth','investment'],x:'Revenue was $62.0 billion and increased 18% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2024-Q2/press-release-webcast'},
  {c:'Microsoft',q:'Q3 FY24',d:'2024-04-25',r:61.9,mc:3.05,pe:35,rx:1.8,t:['ai','cloud','growth','copilot'],x:'Revenue was $61.9 billion and increased 17% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2024-Q3/press-release-webcast'},
  {c:'Microsoft',q:'Q4 FY24',d:'2024-07-30',r:64.7,mc:3.11,pe:36,rx:-1.1,t:['ai','cloud','capex','investment'],x:'Revenue was $64.7 billion and increased 15% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2024-Q4/press-release-webcast'},
  {c:'Microsoft',q:'Q1 FY25',d:'2024-10-30',r:65.6,mc:3.05,pe:35,rx:-6.1,t:['ai','cloud','capex','demand'],x:'Revenue was $65.6 billion and increased 16% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2025-Q1/press-release-webcast'},
  {c:'Microsoft',q:'Q2 FY25',d:'2025-01-29',r:69.6,mc:3.09,pe:34,rx:-6.2,t:['ai','cloud','growth','investment'],x:'Revenue was $69.6 billion and increased 12% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2025-Q2/press-release-webcast'},
  {c:'Microsoft',q:'Q3 FY25',d:'2025-04-30',r:70.1,mc:3.17,pe:35,rx:7.6,t:['ai','cloud','demand','margin'],x:'Revenue was $70.1 billion and increased 13% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2025-Q3/press-release-webcast'},
  {c:'Microsoft',q:'Q4 FY25',d:'2025-07-30',r:76.4,mc:3.84,pe:39,rx:4.0,t:['ai','cloud','capex','growth'],x:'Revenue was $76.4 billion and increased 18% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2025-Q4/press-release-webcast'},
  {c:'Microsoft',q:'Q1 FY26',d:'2025-10-29',r:77.7,mc:3.95,pe:38,rx:-2.9,t:['ai','cloud','investment','openai'],x:'Revenue was $77.7 billion and increased 18% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q1/press-release-webcast'},
  {c:'Microsoft',q:'Q2 FY26',d:'2026-01-28',r:81.3,mc:3.62,pe:34,rx:-8.5,t:['ai','cloud','openai','margin'],x:'Revenue was $81.3 billion and increased 17% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q2/press-release-webcast'},
  {c:'Microsoft',q:'Q3 FY26',d:'2026-04-29',r:82.9,mc:3.78,pe:35,rx:5.3,t:['ai','cloud','demand','growth'],x:'Revenue was $82.9 billion and increased 18% year-over-year.',u:'https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q3/press-release-webcast'},

  {c:'Apple',q:'Q1 FY24',d:'2024-02-01',r:119.6,mc:2.90,pe:29,rx:-0.5,t:['services','iphone','growth','china'],x:'The Company posted quarterly revenue of $119.6 billion, up 2 percent year over year.',u:'https://www.apple.com/newsroom/2024/02/apple-reports-first-quarter-results/'},
  {c:'Apple',q:'Q2 FY24',d:'2024-05-02',r:90.8,mc:2.80,pe:28,rx:6.0,t:['services','capital returns','buyback','growth'],x:'The Company posted quarterly revenue of $90.8 billion, down 4 percent year over year.',u:'https://www.apple.com/newsroom/2024/05/apple-reports-second-quarter-results/'},
  {c:'Apple',q:'Q3 FY24',d:'2024-08-01',r:85.8,mc:3.35,pe:34,rx:-4.8,t:['services','ai','apple intelligence','growth'],x:'The Company posted quarterly revenue of $85.8 billion, up 5 percent year over year.',u:'https://www.apple.com/newsroom/2024/08/apple-reports-third-quarter-results/'},
  {c:'Apple',q:'Q4 FY24',d:'2024-10-31',r:94.9,mc:3.40,pe:37,rx:-1.3,t:['services','iphone','apple intelligence','growth'],x:'The Company posted quarterly revenue of $94.9 billion, up 6 percent year over year.',u:'https://www.apple.com/newsroom/2024/10/apple-reports-fourth-quarter-results/'},
  {c:'Apple',q:'Q1 FY25',d:'2025-01-30',r:124.3,mc:3.55,pe:38,rx:-3.2,t:['services','iphone','apple intelligence','china'],x:'The Company posted quarterly revenue of $124.3 billion, up 4 percent year over year.',u:'https://www.apple.com/newsroom/2025/01/apple-reports-first-quarter-results/'},
  {c:'Apple',q:'Q2 FY25',d:'2025-05-01',r:95.4,mc:3.12,pe:33,rx:-3.7,t:['services','capital returns','tariffs','risk'],x:'The Company posted quarterly revenue of $95.4 billion, up 5 percent year over year.',u:'https://www.apple.com/newsroom/2025/05/apple-reports-second-quarter-results/'},
  {c:'Apple',q:'Q3 FY25',d:'2025-07-31',r:94.0,mc:3.21,pe:34,rx:2.1,t:['services','iphone','growth','margin'],x:'The Company posted quarterly revenue of $94.0 billion, up 10 percent year over year.',u:'https://www.apple.com/newsroom/2025/07/apple-reports-third-quarter-results/'},
  {c:'Apple',q:'Q4 FY25',d:'2025-10-30',r:102.5,mc:3.85,pe:39,rx:1.7,t:['services','iphone','ai','growth'],x:'The Company posted quarterly revenue of $102.5 billion, up 8 percent year over year.',u:'https://www.apple.com/newsroom/2025/10/apple-reports-fourth-quarter-results/'},
  {c:'Apple',q:'Q1 FY26',d:'2026-01-29',r:143.8,mc:4.10,pe:41,rx:3.0,t:['services','iphone','ai','growth'],x:'The Company posted quarterly revenue of $143.8 billion, up 16 percent year over year.',u:'https://www.apple.com/newsroom/2026/01/apple-reports-first-quarter-results/'},
  {c:'Apple',q:'Q2 FY26',d:'2026-04-30',r:111.2,mc:4.18,pe:39,rx:2.4,t:['services','iphone','growth','margin'],x:'The Company posted quarterly revenue of $111.2 billion, up 17 percent year over year.',u:'https://www.apple.com/newsroom/2026/04/apple-reports-second-quarter-results/'}
];

const themes=[
  {n:'01',icon:'↗',name:'AI as the demand engine',desc:'AI moved from product feature to infrastructure cycle, cloud workload and device experience.',tags:['ai','data center','cloud','apple intelligence'],count:'22 / 30'},
  {n:'02',icon:'◫',name:'Capacity before payoff',desc:'Investment rises ahead of monetization: GPUs, data centers, custom silicon and device R&D.',tags:['investment','capex','supply'],count:'17 / 30'},
  {n:'03',icon:'≈',name:'Margins under scrutiny',desc:'Each company frames mix, efficiency and supply costs as the bridge from growth to profit.',tags:['margin'],count:'11 / 30'},
  {n:'04',icon:'◎',name:'Ecosystems compound',desc:'CUDA, Azure and Services deepen retention while widening each platform’s revenue surface.',tags:['services','cloud','data center'],count:'19 / 30'},
  {n:'05',icon:'△',name:'Constraints stay visible',desc:'China, supply, tariffs and the timing of infrastructure returns recur as downside language.',tags:['china','risk','supply','tariffs'],count:'13 / 30'}
];

document.querySelector('#theme-grid').innerHTML=themes.map(t=>`<article class="theme-card"><span class="theme-number">${t.n}</span><div class="theme-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><footer><span>${t.tags[0].toUpperCase()}</span><span>${t.count}</span></footer></article>`).join('');

const synonyms={ai:['ai','artificial intelligence','copilot','blackwell','rubin','apple intelligence'],risk:['risk','china','tariffs','constraint','supply'],investment:['investment','capex','capital spending','infrastructure'],growth:['growth','revenue','demand'],margin:['margin','profit','operating income'],services:['services','cloud','azure','ecosystem'],returns:['capital returns','buyback','shareholder','dividend']};
function termsFor(q){const s=q.toLowerCase();const terms=s.match(/[a-z]+/g)||[];Object.entries(synonyms).forEach(([k,v])=>{if(s.includes(k)||v.some(x=>s.includes(x)))terms.push(...v)});return [...new Set(terms.filter(x=>x.length>2))]}
function searchReports(query,selected){const terms=termsFor(query);return reports.filter(r=>selected.includes(r.c)).map(r=>{const hay=(r.x+' '+r.t.join(' ')+' '+r.c+' '+r.q).toLowerCase();return {...r,score:terms.reduce((s,t)=>s+(hay.includes(t)?(t.length>5?3:1):0),0)}}).sort((a,b)=>b.score-a.score||b.d.localeCompare(a.d)).slice(0,6)}
function synthesize(results,q){const cs=[...new Set(results.map(r=>r.c))];const tags={};results.forEach(r=>r.t.forEach(t=>tags[t]=(tags[t]||0)+1));const top=Object.entries(tags).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0]);if(!results.some(r=>r.score))return `No direct phrase match was found. Showing the latest releases from ${cs.join(', ')} so you can inspect the source language.`;return `Across ${cs.join(', ')}, the strongest matching signals are ${top.join(', ')}. The releases consistently tie those themes to revenue expansion, while the emphasis differs: NVIDIA centers infrastructure demand, Microsoft centers cloud adoption, and Apple centers products plus Services. Inspect the exact blocks below.`}
function runQuery(q){const selected=[...document.querySelectorAll('.query-options input:checked')].map(x=>x.value);const answer=document.querySelector('#answer');if(!q.trim()){answer.innerHTML='<div class="answer-empty"><p>Enter a question to scan the reports.</p></div>';return}const found=searchReports(q,selected);answer.innerHTML=`<div class="answer-head"><strong>ANSWER</strong><span>${found.length} SOURCE BLOCKS</span></div><p class="answer-summary">${synthesize(found,q)}</p><div class="evidence-list">${found.map(r=>`<article class="evidence"><div class="evidence-top"><strong>${r.c.toUpperCase()} / ${r.q}</strong><span>${r.d}</span></div><blockquote>“${r.x}”</blockquote><a href="${r.u}" target="_blank" rel="noopener">Open official release ↗</a></article>`).join('')}</div>`}
document.querySelector('#query-form').addEventListener('submit',e=>{e.preventDefault();runQuery(document.querySelector('#query-input').value)});
document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#query-input').value=b.dataset.query;runQuery(b.dataset.query);document.querySelector('#ask').scrollIntoView({behavior:'smooth'})}));

let metric='revenue',activeIndex=9;
const labels={revenue:['Quarterly revenue ($B)','$','B'],marketCap:['Approx. post-report market cap ($T)','$','T'],pe:['Approx. trailing P/E ratio','', 'x']};
function grouped(){return Object.keys(companies).map(c=>({c,rows:reports.filter(r=>r.c===c)}))}
function fmt(v,m=metric){return m==='revenue'?`$${v.toFixed(1)}B`:m==='marketCap'?`$${v.toFixed(2)}T`:`${v.toFixed(0)}x`}
function drawChart(){const svg=document.querySelector('#market-chart');const groups=grouped(),W=1120,H=480,p={l:62,r:30,t:24,b:56};const vals=groups.flatMap(g=>g.rows.map(r=>r[metric==='revenue'?'r':metric==='marketCap'?'mc':'pe']));const max=Math.max(...vals)*1.12,min=metric==='revenue'?0:Math.min(...vals)*.84;const x=i=>p.l+i*(W-p.l-p.r)/9,y=v=>p.t+(max-v)/(max-min)*(H-p.t-p.b);let out='';for(let i=0;i<5;i++){const val=min+(max-min)*(4-i)/4,yy=p.t+i*(H-p.t-p.b)/4;out+=`<line class="grid-line" x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}"/><text class="axis-label" x="${p.l-12}" y="${yy+4}" text-anchor="end">${fmt(val)}</text>`}for(let i=0;i<10;i++){out+=`<text class="axis-label" x="${x(i)}" y="${H-18}" text-anchor="middle">R${i+1}</text>`}groups.forEach(g=>{const key=metric==='revenue'?'r':metric==='marketCap'?'mc':'pe',pts=g.rows.map((r,i)=>`${x(i)},${y(r[key])}`).join(' '),color=companies[g.c].color;out+=`<polyline class="series-line" points="${pts}" stroke="${color}"/>`;g.rows.forEach((r,i)=>out+=`<circle class="series-point" data-company="${g.c}" data-index="${i}" cx="${x(i)}" cy="${y(r[key])}" r="${i===activeIndex?7:5}" fill="${color}"/>`) });svg.innerHTML=`<title id="chart-title">${labels[metric][0]}</title><desc id="chart-desc">Ten report sequence comparison for NVIDIA, Microsoft and Apple.</desc>${out}`;document.querySelector('#chart-note').textContent=labels[metric][0];svg.querySelectorAll('.series-point').forEach(pt=>{pt.addEventListener('mouseenter',showTip);pt.addEventListener('mouseleave',()=>document.querySelector('#chart-tooltip').hidden=true);pt.addEventListener('click',()=>{activeIndex=+pt.dataset.index;drawChart();renderSnapshot()})})}
function showTip(e){const r=reports.filter(x=>x.c===e.target.dataset.company)[+e.target.dataset.index],key=metric==='revenue'?'r':metric==='marketCap'?'mc':'pe',tip=document.querySelector('#chart-tooltip'),box=document.querySelector('.chart-wrap').getBoundingClientRect();tip.innerHTML=`<strong>${r.c} · ${r.q}</strong><br>${fmt(r[key])}<br><span>${r.d}</span>`;tip.hidden=false;tip.style.left=Math.min(e.clientX-box.left+12,box.width-170)+'px';tip.style.top=(e.clientY-box.top-65)+'px'}
function renderSnapshot(){document.querySelector('#snapshot').innerHTML=grouped().map(g=>{const r=g.rows[activeIndex],prev=g.rows[Math.max(0,activeIndex-1)],key=metric==='revenue'?'r':metric==='marketCap'?'mc':'pe',delta=activeIndex===0?0:(r[key]-prev[key])/prev[key]*100;return `<article class="snapshot-card"><header><strong>${g.c}</strong><span>${r.q} · ${r.d}</span></header><div class="snapshot-value">${fmt(r[key])}</div><div class="snapshot-delta">${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1)}% vs prior report snapshot · stock ${r.rx>=0?'+':''}${r.rx}% after report</div></article>`}).join('')}
document.querySelectorAll('.metric-switch button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.metric-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');metric=b.dataset.metric;drawChart();renderSnapshot()}));
drawChart();renderSnapshot();
